### PR TITLE
Update basics.tex

### PR DESCRIPTION
**Pull request by prime235711**
Missing parenthesis

### CODE REVIEW

**Comment by prime235711** [comment]
This is according to the issue i proposed.
https://github.com/HoTT/book/issues/1100

**Comment by awodey** [comment]
thanks!

**Comment by mikeshulman** [comment]
Wait a minute, shouldn't this be `$(\sm{x:A}P(x))\to A$`, not `$\sm{x:A}(P(x))\to A$`?

**Comment by prime235711** [comment]
Oh, you're right. My bad. How should I change that? Should I revert previous merge and resubmit a PR?

**Comment by mikeshulman** [comment]
Either that, or just submit a new PR that changes it to the correct one.

**Pull request merged**
