### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by danielgerigk**

### CODE REVIEW

**Comment by pthariensflame** [comment]
The `true`s and `false`s were correct before.

**Comment by danielgerigk** [comment]
@pthariensflame i don't think so. ;)

**Comment by mikeshulman** [comment]
I think @danielgerigk is right.  esucc originally went from odd to even, so its indexed version should go from paritynat(1) to paritynat(0).

**Comment by pthariensflame** [comment]
Oh, OK.  I guess I was reading it wrong; sorry!

**Pull request merged**
