### PR TITLE
if and only if

### PR DESCRIPTION
**Pull request by danielgerigk**
"Read logically, this says that two pairs are equal if and only if they are equal componentwise."

### CODE REVIEW

**Comment by awodey** [comment]
it could as well say "just if" or "just in case".

**Comment by awodey** [comment]
please provide descriptions of the pull requests.

**Comment by danielgerigk** [comment]
@awodey Okay, I'll resubmit this one. Shall I write "just if", "just in case" or "if and only if"?

**Comment by awodey** [comment]
let’s go with “just if”
thanks!

**Pull request closed without merging**
