### PR TITLE
Add remark about lack of eta in A.1, close #995

### LINKED ISSUE #995: Include eta-conversion in A.1
Jugmental eta-conversion for functions (which is assumed in the main body of the text) seems to be missing from the first presentation of syntax in appendix A.1?  If it's there, it's so cleverly hidden that I can't see it.

### PR DESCRIPTION
**Pull request by mikeshulman**

### CODE REVIEW

**Comment by cangiuli** [comment]
Maybe replace "dependent on the type" with "sensitive to the type" to avoid any potential confusion over the word "dependent"?

**Comment by mikeshulman** [comment]
Sure, done.

**Comment by cangiuli** [comment]
@mikeshulman This PR is still open, but I think everyone was happy with it -- should we merge?

**Comment by DanGrayson** [comment]
lgtm

**Pull request merged**
