### PR TITLE
Fix a few things about the surreal numbers

### PR DESCRIPTION
**Pull request by mikeshulman**
While formalizing the surreal numbers, I noticed some typos and an omission from the definition of addition.

### CODE REVIEW

**Comment by andrejbauer** [comment]
You're formalizing the surreal numbers? Wow, how painful is it?

**Comment by mikeshulman** [comment]
It's not as bad as you might think; I submitted a PR to the HoTT Coq repo.

**Comment by mikeshulman** [comment]
bump

**Comment by mikeshulman** [comment]
bump again.  I'd especially like to get this merged before updating the posted version since it is an actual mathematical error.

**Comment by andrejbauer** [comment]
Must it be me who digs into this and proof reads the changes?

**Comment by EgbertRijke** [comment]
I'm not yet at the changes, but I found a typo of the form "which it is" on line 2725.

I'm reading the whole thing.

**Comment by mikeshulman** [comment]
I don't think "which it is" was a typo.

> We will also need the joint recursion principle, \define{$(\NO,\le,<)$-recursion}, which it is convenient to state as follows.

I.e. we will need the joint recursion principle, and it is convenient to state the joint recursion principle as follows.  But if that's unclear, it could probably be rephrased somehow.

**Comment by mikeshulman** [comment]
Thanks for reading it!!

**Comment by mikeshulman** [comment]
I've fixed all your suggestions.  Thanks for reading it!!

**Pull request merged**
