### PR TITLE
correction of a nasty equation concerning the higher groupoid structu…

### PR DESCRIPTION
**Pull request by danielgerigk**
…re of product types

### CODE REVIEW

**Comment by danielgerigk** [comment]
I've triple-checked everything, and I'm still failing to see the book version as being correct.

**Comment by mikeshulman** [comment]
I checked it in Coq at the time that I wrote it, because it was so complicated and I wanted to be sure to get it right: it's [here](https://github.com/HoTT/HoTT/blob/master/theories/Types/Prod.v#L172).  The Coq version uses `ap011` instead of `ap` because its `path_prod` is curried, but you can check that the book's version is also right by replacing the line

```coq
 = ap011 (path_prod u w) (concat_pp_p p q r) (concat_pp_p p' q' r')
```

by

```coq
  = ap (fun z => path_prod u w (fst z) (snd z)) (path_prod' (concat_pp_p p q r) (concat_pp_p p' q' r'))
```

**Comment by danielgerigk** [comment]
Ok I trust you (and Coq). But the other corrections are correct, are they?

**Comment by mikeshulman** [comment]
yes.  thanks!

**Comment by mikeshulman** [comment]
If you want an explanation, `\pairpath(\ctassoc(p,q,r),\ctassoc(p',q',r'))` is a path between pairs of paths, whereas we need a path between paths between pairs.

**Comment by danielgerigk** [comment]
thanks, now I feel dizzy.

**Pull request merged**
