### PR TITLE
disambiguate 'id' and 'Id'

### PR DESCRIPTION
**Pull request by jeffersoncarpenter**
They differ only by capitalization.  A sentence like this one would have helped me as I read through the first chapter.

### CODE REVIEW

**Comment by mikeshulman** [comment]
The lower-case one is used an order of magnitude more in the book (the identity type is usually written with "="), so I would be inclined to put the disambiguation remark near the introduction of the upper-case one instead.

**Comment by andrejbauer** [comment]
I concur with @mikeshulman, let's have a remark next to `Id`.

**Comment by jeffersoncarpenter** [comment]
Moved the remark, and updated the branch.

**Comment by mikeshulman** [comment]
Thanks!

**Pull request merged**
