### PR TITLE
Clarify that the universe U is itself a type

### PR DESCRIPTION
**Pull request by GeoffChurch**
I thought the universe U might be a different sort of object (like a collection instead of a set) until I read "Like any type" in the next sentence.

### CODE REVIEW

**Comment by martinescardo** [comment]
The new sentence says "universe type" but I think it should be "type universe" to follow common parlance.

**Comment by martinescardo** [comment]
But perhaps it would be better to completely rewrite the sentence.

**Comment by mikeshulman** [comment]
I think "universe type" sounds just fine.  Don't we talk about "function types", "pair types", "natural numbers types", etc.?  I suppose to be really consistent with those it should be "type type", but ugh.

**Comment by mikeshulman** [comment]
The point of saying "universe type" is that the universe itself *is* a type.  In "type universe" the word "type" refers rather to the *elements* of the universe.

**Comment by mikeshulman** [comment]
However, I'd be happy to hear suggestions for better ways to rewrite the sentence.

**Comment by DanGrayson** [comment]
Maybe something like "In type theory, one can have a type whose elements are themselves types; such a type is called a \emph{universe} and is usually denoted by $\UU$."

**Comment by RobertHarper** [comment]
This sounds the most appealing to me, and is often the way I describe them.  Such types whose elements are types need not be “universal”, though; the empty type is a universe, for example.  Nevertheless, I think that the formulation Dan proposes is good.

(c) Robert Harper.  All Rights Reserved.

**Comment by mikeshulman** [comment]
Thanks Dan; see #1076.

**Comment by DanGrayson** [comment]
I think the empty type is not a universe.  If it were, then in a context where a variable X has been declared to be an element of the empty type, we could use it as a type, adding, for example, a variable f of type X->X to the context and verifying that the new context is well-formed.

**Comment by RobertHarper** [comment]
Good point, I meant only that one could have an empty universe.

(c) Robert Harper.  All Rights Reserved.

**Pull request merged**
