### PR TITLE
Fix typo, missing parenthesis in transport

### PR DESCRIPTION
**Pull request by jonaprieto**
`\trans{p}{_}` is a unary-function.

### CODE REVIEW

**Comment by mikeshulman** [comment]
I think this is not a typo, but just a standard abuse of notation in mathematics; I'm sure we've used it in many other places in the book too.  I suppose we should remark on it somewhere though, if we didn't.

**Comment by jonaprieto** [comment]
> I'm sure we've used it in many other places in the book too
This is the only usage of this transport with pairs. I searched in all the text files with a regex.

**Comment by mikeshulman** [comment]
I'm not just talking about transport, but about arbitrary functions of two variables.

**Comment by jonaprieto** [comment]
Oh yes, you're right. I found other places in the book with this same issue, e.g. some lemmas in Section 6.12, but for consistency, I'd use parenthesis.

**Comment by mikeshulman** [comment]
Actually, I think one of the points of the book is that using type theory as a foundation for mathematics doesn't require us to be any more pedantic about such things than mathematicians usually are.  But, as I said, it might be helpful to mention this abuse of notation somewhere towards the beginning.

**Comment by mikeshulman** [comment]
Actually, this is already mentioned in section 1.5:

> However, later on in the book we will often write $g(a,b)$ both for functions on a product and for curried functions of two variables.

**Pull request closed without merging**
