### PR TITLE
improve wording in intro about the simplicial interpretation

### PR DESCRIPTION
**Pull request by mikeshulman**
This is a proposal to fix one of the other wording problems raised at #773.  I didn't fully understand the objection to the existing sentence, though, so I may not have actually fixed the problem; please let me know.

### CODE REVIEW

**Comment by vladimirias** [comment]
LGTM

**Comment by andrejbauer** [comment]
Look good. Do we need to put in references to Church and Hofmann & Streicher? It's not a research paper, and we're in the introduction, so too many references can be off-putting.

**Comment by mikeshulman** [comment]
I don't think we *need* to, certainly not in this PR.  There are citations to both of them elsewhere in the intro, I think.

**Comment by mikeshulman** [comment]
There were two acks and no disagreement, so I'm going to merge this.

**Pull request merged**
