### PR TITLE
Present set theory as type theory with one type

### PR DESCRIPTION
**Pull request by VincentSe**
This pull request explains that the 2 layers of set theory come from the unique type available there: set.

### CODE REVIEW

**Comment by DanGrayson** [comment]
I think I can see why this rephrasing has been proposed, but the new version has its own problems.

"All mathematical objects are interpreted as sets, except propositions and proofs."  

In set theory, we don't think of propositions and proofs as mathematical objects.

"By contrast, having different types allows to reintegrate propositions and proofs into the same layer as the other mathematical objects."

It should be stated that we are contrasting type theory with set theory.

The phrase "different types" conveys no more information than the phrase "types", because "types" is plural.

The use of "reintegrate" rather than "integrate" implies that propositions and proofs were formerly (before ZFC) part of the same layer as the mathematical objects.

The verb "allows" is transitive and takes an object.

Saying "as the other mathematical objects" here implies that propositions and proofs are mathematical objects.

"The number 2 becomes of type ``natural number'', the Pythagorean theorem of type ``proposition'' and its proof of type ``Pythagorean theorem''. Therefore type theory is its own deductive system: it need not be formulated inside any superstructure, such as first-order logic."

Using "therefore" here is a bit too strong -- it sounds like something is being proven, but rather, the conclusion is just being illustrated.  The original version put that concluding statement first, so it sounds more forceful.

**Comment by mikeshulman** [comment]
> I think I can see why this rephrasing has been proposed

I can't.  What are you trying to achieve here?

**Comment by awodey** [comment]
I don’t think the original is in need of improvement, and anyway this is not an improvement.

**Comment by VincentSe** [comment]
The aim of this pull request is to ease the transition from set theory to type theory for classical mathematicians. I agree with all @DanGrayson remarks and can integrate them in the PR.

**Comment by mikeshulman** [comment]
But exactly what difficulty have you encountered in that transition that you are trying to ease?

**Comment by VincentSe** [comment]
I hear from classical mathematicians that type theory is so different from set theory that they don't even try to read it. Albeit simplified, presenting set theory as a type theory with just one type seems a powerful motive to switch to type theory. Even more so by showing that the logical layer in set theory was just a backdoor to bring back propositional types. In other words, classical mathematicians wanted types, but they didn't know it.

**Comment by mikeshulman** [comment]
Why don't you write a little note or blog post of your own explaining that point of view?

**Comment by VincentSe** [comment]
Well, probably for the same reason that you and others wrote the HoTT book, instead of writing scattered blog posts about HoTT.

**Comment by telephon** [comment]
As far as I can tell, in ZFC-style set theory, there is no such thing as a type. Sets are not even explicitly defined. I would find it rather misleading to say that no type is the same as one single type.

**Comment by awodey** [comment]
A good place for this sort of discussion is homotopytypetheory@googlegroups.com, or in the comments following a blog post on homotopytypetheory.org, or on the new HoTT Zulip.  But not in the HoTT book, which - except for typos and corrections of proofs - is pretty settled.

**Pull request closed without merging**
