### PR TITLE
P in the flattening lemma is defined *recursively*, not inductively

### PR DESCRIPTION
**Pull request by mikeshulman**
(unless I'm crazy)

### CODE REVIEW

**Comment by andrejbauer** [comment]
Oh, we could split hairs here since recursion is a non-dependent induction.

**Comment by mikeshulman** [comment]
Hmm, to me "X is defined inductively" means that X is an inductive type, not that X is a dependent function defined using the induction principle of its domain.

**Comment by andrejbauer** [comment]
Ah, this never occurred to me because I looked at `P : W -> Type` and thought immediately of dependent vs. non-dependent function issue. A type family *is* a function.

**Comment by mikeshulman** [comment]
Of course, but there are also inductive families.

**Pull request merged**
